# Generated by Django 5.2 on 2025-06-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='پہلا نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='آخری نام')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name='پورا نام')),
                ('address', models.CharField(max_length=150, verbose_name='پتہ')),
                ('phone', models.CharField(max_length=20, verbose_name='فون نمبر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ای میل')),
                ('password', models.CharField(max_length=100, verbose_name='پاس ورڈ')),
                ('password_again', models.CharField(max_length=100, verbose_name='پاس ورڈ دوبارہ درج کریں')),
                ('status', models.CharField(blank=True, default='shop_keeper', max_length=20, verbose_name='حیثیت')),
                ('fake_id', models.IntegerField(blank=True, verbose_name='جعلی آئی ڈی')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_profile', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
