# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerByer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='byer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('byer_read', models.BooleanField(default=False)),
                ('seller_read', models.BooleanField(default=False)),
                ('reciver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('message_header', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_header', to='shoping.sellerbyer')),
            ],
        ),
        migrations.CreateModel(
            name='SellProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('condition', models.CharField(choices=[('Used Excellent condition', 'استعمال شدہ - بہترین حالت'), ('New', 'نیا'), ('Like New', 'نیا جیسا'), ('Not working', 'خراب'), ('Used Good condition', 'استعمال شدہ - اچھی حالت')], default='New', max_length=40, null=True, verbose_name='حالت')),
                ('category', models.CharField(blank=True, choices=[('services', 'سروسز'), ('appliances', 'آلات'), ('furniture', 'فرنیچر'), ('books', 'کتابیں'), ('fashion', 'فیشن'), ('electronics', 'الیکٹرانکس'), ('statinory', 'اسٹیشنری'), ('kitchen', 'کچن آئٹمز'), ('mobile', 'موبائل'), ('toys', 'کھلونے'), ('property', 'جائیداد'), ('fabrics', 'کپڑے'), ('accessories', 'لوازمات'), ('beauty', 'خوبصورتی'), ('vehicles', 'گاڑیاں'), ('sports', 'کھیل'), ('car', 'کار')], default='mobile', max_length=20, null=True, verbose_name='زمرہ')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='لوکیشن')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفصیلات')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
        ),
        migrations.AddField(
            model_name='sellerbyer',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shoping.sellproductmodel'),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='im.jpg', upload_to='product_images', verbose_name='Image')),
                ('product_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shoping.sellproductmodel')),
            ],
        ),
    ]
