# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='دکان کا نام')),
                ('shop_address', models.CharField(max_length=200, verbose_name='پتہ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='فون نمبر')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('booking', models.BooleanField(blank=True, default=True, null=True, verbose_name='بکنگ')),
                ('price', models.IntegerField(blank=True, default=1000, verbose_name='قیمت')),
                ('map_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='نقشہ لنک')),
                ('more_information', models.CharField(blank=True, max_length=600, null=True, verbose_name='مزید معلومات')),
                ('image', models.ImageField(blank=True, default='default_shop.jpeg', null=True, upload_to='shop_images', verbose_name='تصویر')),
                ('shop_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.loginmodel', verbose_name='مالک')),
            ],
        ),
    ]
