# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='فون نمبر')),
                ('customer_address', models.CharField(max_length=150, verbose_name='پتہ')),
                ('password', models.CharField(max_length=100, verbose_name='پاس ورڈ')),
                ('serial_number', models.IntegerField(verbose_name='سیریل نمبر')),
                ('date_time', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.addshopmodel', verbose_name='دکان')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.addcustomermodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.addshopmodel')),
            ],
        ),
    ]
