# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karigars', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(blank=True, choices=[('shop', 'shop'), ('karigar', 'karigar')], max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('karigar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='karigars.registerkarigarmodel')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.addshopmodel')),
            ],
        ),
    ]
