# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMeasurementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambayi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='لمبائی')),
                ('choriyi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='چوڑائی')),
                ('chest', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='چھاتی')),
                ('bazoo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='بازو')),
                ('asteen', models.CharField(choices=[('kaf', 'کاف'), ('double_kaf', 'ڈبل کاف'), ('gool', 'گول'), ('kani', 'کانی'), ('other', 'دیگر')], default='kaf', max_length=20, verbose_name='آستین')),
                ('asteen_choriti', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='آستین چوڑائی')),
                ('monda', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مونڈھا')),
                ('teera', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تیرا')),
                ('gala', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='گلا سائز')),
                ('gala_type', models.CharField(choices=[('half ban', 'ہاف بین'), ('collar', 'کالر'), ('sada', 'سادہ گلا'), ('full ban', 'فل بین'), ('v_gala', 'وی گلا'), ('shabazi', 'شبازی')], default='half ban', max_length=30, verbose_name='گلا قسم')),
                ('shalwar', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='شلوار')),
                ('pancha', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='پانچہ')),
                ('gehra', models.CharField(choices=[('gool', 'گول'), ('chorus', 'چورس'), ('kurta', 'کرتا')], default='gool', max_length=20, verbose_name='گہرا')),
                ('pockets', models.CharField(max_length=100, verbose_name='پاکٹ')),
                ('seelai', models.CharField(choices=[('single', 'سنگل'), ('double', 'ڈبل'), ('triple', 'ٹرپل'), ('ghoom', 'گھوم'), ('chamak', 'چمک داگھہ')], default='single', max_length=20, verbose_name='سلائی')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='باقی معلومات')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.addcustomermodel', verbose_name='کسٹمر')),
            ],
        ),
    ]
