# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.IntegerField(default=0, verbose_name='پرانا بقایا')),
                ('total_price', models.IntegerField(default=0, verbose_name='کل قیمت')),
                ('advance', models.IntegerField(default=0, verbose_name='ایڈوانس')),
                ('remining', models.IntegerField(default=0, verbose_name='بقایا')),
                ('order_number', models.IntegerField(default=0, verbose_name='آرڈر نمبر')),
                ('delivery_date', models.DateField(verbose_name='ترسیل کی تاریخ')),
                ('details', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='تفصیلات')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customers.addcustomermodel', verbose_name='کسٹمر')),
            ],
        ),
    ]
