# Generated by Django 5.2 on 2025-06-26 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKarigarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='فون')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='ای میل')),
                ('address', models.CharField(max_length=150, verbose_name='پتہ')),
                ('password', models.CharField(max_length=100, verbose_name='پاس ورڈ')),
                ('password_again', models.CharField(max_length=100, verbose_name='پاس ورڈ دوبارہ درج کریں')),
                ('experience', models.TextField(null=True, verbose_name='اپنے بارے میں')),
                ('karigar_date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('fake_id', models.IntegerField(blank=True, null=True, verbose_name='جعلی آئی ڈی')),
                ('status', models.CharField(blank=True, default='karigar', max_length=20, verbose_name='حیثیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='karigar', verbose_name='تصویر')),
                ('karigar_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.addshopmodel', verbose_name='دکان')),
            ],
        ),
    ]
